[package]
name = "git-task"
version = "0.1.0"
edition = "2021"

[lib]
name = "gittask"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
enable-ansi-support = "0.2.1"
futures-util = "0.3"
git2 = "0.19.0"
graphql_client = { version = "0.14", features = ["reqwest-blocking"] }
nu-ansi-term = "0.50"
octocrab = { version = "0.39.0", features = ["stream"] }
regex = "1.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
tokio = { version = "1.39", features = ["rt-multi-thread"] }
log = "0.4.22"