[package]
name = "git-task"
version = "0.1.0"
edition = "2021"

[lib]
name = "gittask"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
git2 = "0.19.0"
nu-ansi-term = "0.50"
octocrab = { version = "0.39.0", features = ["stream"] }
regex = "1.1"
serde_json = "1.0"
tokio = { version = "1.39", features = ["rt-multi-thread"] }
futures-util = "0.3.30"